#!/bin/bash
#set -x

[[ $1 == '-h' ]] && {
    cat <<EOF
   bpods [job-name [job-name ...]]
      display the pod names of the specified batch jobs if no jobs are
      specified then the pods of all current batch jobs will
      be displayed.
   See repository README.md for more documentation and examples.
EOF
    
    exit 0
}
jobs=( $@ )

(( ! ${#jobs[@]} )) && {
   jobs=( $(oc get jobs -o name) )
}

for j in ${jobs[@]}; do 
  j=${jobs##*/}
  oc get pods -l job-name=$j -o name
done
